:concurrency: 12
staging:
  :concurrency: 12
production:
  :concurrency: 12
:queues:
  - ["broadcaster", 6]
  - ["high_level_scraper", 4]
  - ["low_level_scraper", 4]
  - ["mailers", 2]
  - ["low", 1]