:concurrency: 7
staging:
  :concurrency: 2
production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 2 } %>
:queues:
  - ["broadcaster", 6]
  - ["high_level_scraper", 4]
  - ["low_level_scraper", 4]
  - ["mailers", 2]
  - ["low", 1]